---

server:
  hosts:
    docker:
      ansible_user: vagrant
      ansible_host: localhost
      ansible_port: 2222
      ansible_ssh_private_key_file: /home/cbarbieri/Projetos/VMServer/.vagrant/machines/docker/vmware_desktop/private_key
    db:
      ansible_user: vagrant
      ansible_host: localhost
      ansible_port: 2200
      ansible_ssh_private_key_file: /home/cbarbieri/Projetos/VMServer/.vagrant/machines/db/vmware_desktop/private_key
