- hosts: docker
  become: true
  tasks:
    - name: Install docker dependencies
      apt: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - "apt-transport-https"
        - "ca-certificates"
        - "curl"
        - "gnupg"
        - "lsb-release"
        - "python3-pip"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt packages
      apt:
        update_cache: true

    - name: Install Docker Engine
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items: 
        - "docker-ce"
        - "docker-ce-cli"
        - "containerd.io"
        - "docker-compose-plugin"

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Add administrator to docker group
      user:
        name: "vagrant"
        groups: docker
        append: yes

    - name: Clone repository
      git:
        clone: yes 
        repo: https://github.com/caiolombello/fullstack-docker.git
        dest: fullstack-docker

    - name: Deploying docker-compose
      shell: docker compose -f ./fullstack-docker/docker-compose.yml up -d

- hosts: db
  become: true
  tasks:
    - name: Required packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - "mysql-server"
        - "python3"
        - "python3-pip"
        - "gcc"
    
    - name: Install Required pip modules
      pip:
        name:
          - PyMySQL
        state: present
        executable: pip3
    
    - name: Run MySQL
      systemd:
        name: mysql
        state: started
        enabled: true



